apiVersion: v1
kind: Service
metadata:
  labels:
    app: musicstore-website
  name: musicstore-website
  namespace: musicstore
spec:
  ports:
  - nodePort: 32000
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: musicstore-website
  type: NodePort
